### ISSUE TITLE
Can i ask something? About library issues.

### ISSUE THREAD

**Issue by herald25santos** [Petrulak/kotlin-mvp-clean-architecture#16]
I've had been tried your clean architecture. I cannot call Timber library to application which is belong to presentation module? you declared timber library in gradle domain module. What should I do? thanks in advance.

**Comment by Petrulak** [comment]
Hello. So timber does not work in presentation (app) module? 
It should work since timber dependency is declared in domain module, and presentation(app) module uses domain module.
Can you check for don't have some filters on in LogCat? For example, searching for some text etc.

**Comment by herald25santos** [comment]
Yeah that's right but I cannot find Timber library also I already compile it in dependencies(presentation build.gradle).

**Comment by Petrulak** [comment]
So if you type `Timbe.e("whaever")` in your app module, it doesn't recognize the library?
If you go to `com.petrulak.cleankotlin.ui.example1.Example1Activity` you can find some timber usage here, for example `Timber.i("Parcelable  message = ${it.message}")`.

**Comment by herald25santos** [comment]
Yes exactly I don't know what happened I just follow your way of implementation in the gradle but it didn't works.

**Comment by Petrulak** [comment]
Ok, seems like something on your local set up is no right. Did you change anything? Can you try to clean the project? (`./gradlew clean` in terminal or via the button in Android Studio). If this doesn't work can you try `Invalidate Caches/Restart..` option?

**Comment by herald25santos** [comment]
Sir still not working. I didn't change anything it's so weird haha btw thanks I'll try to figure out this kind of issue.

**Comment by herald25santos** [comment]
FYI sir Petrulak I fixed this by changing from implementation to api when declaring timber in gradle dependencies. I used build gradle version 3.1.1 that's why I used implementation instead of api thanks :D

**Comment by Petrulak** [comment]
Good to hear that ! :)

**Comment by herald25santos** [comment]
Hello again sir :). Do you have example on how to use interactor even at least on of these given interactor  CompletableInteractor, FlowableInteractor and SingleInteractor? when do we use it? So far this is the best MVP kotlin clean architecture I've ever seen. Thanks in advance.
